package models

// DefaultMenuRules is the factory rule set (seed version 3). Every rule
// carries a sentence template; the Expression strings below are exactly what
// the template renderer produces — a test asserts they never drift.
func DefaultMenuRules() []MenuRule {
	return []MenuRule{
		{
			Code:        "avoid_double_egg",
			Name:        "同餐蛋类最多一道",
			Description: "一餐里最多出现一道蛋类菜，避免番茄炒蛋配蛋花汤。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "constraint",
			Severity:    "hard",
			Relaxable:   false,
			Expression:  `!(has(candidate.protein_sources, "egg")) || countMeal("protein_sources", "egg") < 1`,
			Template:    `{"type":"limit","scope":"meal","category":"egg","n":1,"strength":"must"}`,
			Priority:    10,
			Message:     "同餐蛋类已达到上限",
		},
		{
			Code:        "limit_cold_dishes",
			Name:        "同餐凉菜最多一道",
			Description: "一餐里最多出现一道凉菜冷食。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "constraint",
			Severity:    "hard",
			Relaxable:   false,
			Expression:  `!(candidate.serving_temperature == "cold") || countMeal("serving_temperature", "cold") < 1`,
			Template:    `{"type":"limit","scope":"meal","category":"cold","n":1,"strength":"must"}`,
			Priority:    20,
			Message:     "同餐凉菜已达到上限",
		},
		{
			Code:        "limit_staples",
			Name:        "同餐主食最多一道",
			Description: "米线、炒饭、饼类等主食一餐最多一道。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "constraint",
			Severity:    "hard",
			Relaxable:   false,
			Expression:  `!(candidate.dish_role == "staple") || countMeal("dish_role", "staple") < 1`,
			Template:    `{"type":"limit","scope":"meal","category":"staple","n":1,"strength":"must"}`,
			Priority:    30,
			Message:     "同餐主食已达到上限",
		},
		{
			Code:        "avoid_same_primary_protein",
			Name:        "同餐主蛋白不重样",
			Description: "一餐里尽量不重复同一种主蛋白（豆制品除外），重复时降低排序。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `countOverlapMeal("protein_sources", candidate.protein_sources) >= 1 && !hasOnly(candidate.protein_sources, "soy") ? -14 : 0`,
			Template:    `{"type":"no_repeat","scope":"meal","n":1,"points":14,"strength":"prefer"}`,
			Priority:    40,
			Message:     "同餐主蛋白重复降分",
		},
		{
			Code:        "avoid_heavy_spicy_day",
			Name:        "重油重辣一天最多一道",
			Description: "同一天已有重油重辣菜时，尽量不再安排第二道。",
			Enabled:     true,
			Scope:       "day",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `candidate.spice_level >= 2 && candidate.richness_level >= 2 && countDay("heavy_spicy", "true") >= 1 ? -18 : 0`,
			Template:    `{"type":"limit","scope":"day","category":"heavy_spicy","n":1,"points":18,"strength":"prefer"}`,
			Priority:    210,
			Message:     "同日重油重辣降分",
		},
		{
			Code:        "spicy_meal_spread",
			Name:        "辣菜同餐不扎堆",
			Description: "一餐里已有辣菜时，尽量把其他辣菜留到别的餐。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `candidate.spice_level >= 1 && len(filter(meal, .spice_level >= 1)) >= 1 ? -12 : 0`,
			Template:    `{"type":"limit","scope":"meal","category":"spicy","n":1,"points":12,"strength":"prefer"}`,
			Priority:    220,
			Message:     "同餐辣菜扎堆降分",
		},
		{
			Code:        "slow_meal_spread",
			Name:        "费时菜同餐最多一道",
			Description: "炖煮等超过 45 分钟的菜一餐尽量只安排一道，省得手忙脚乱。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `candidate.cook_time > 45 && len(filter(meal, .cook_time > 45)) >= 1 ? -15 : 0`,
			Template:    `{"type":"limit","scope":"meal","category":"slow","n":1,"points":15,"strength":"prefer"}`,
			Priority:    230,
			Message:     "同餐费时菜过多降分",
		},
		{
			Code:        "weekly_protein_variety",
			Name:        "一周蛋白换着吃",
			Description: "同一种主蛋白一周吃到第 4 次后开始降分，鼓励换口味（豆制品除外）。",
			Enabled:     true,
			Scope:       "week",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `countOverlapWeek("protein_sources", candidate.protein_sources) >= 4 && !hasOnly(candidate.protein_sources, "soy") ? -20 : 0`,
			Template:    `{"type":"no_repeat","scope":"week","n":4,"points":20,"strength":"prefer"}`,
			Priority:    240,
			Message:     "一周同种蛋白过多降分",
		},
		{
			Code:        "weekly_fried_limit",
			Name:        "油炸一周最多两次",
			Description: "一周已有两道油炸菜后，继续安排油炸会降分。",
			Enabled:     true,
			Scope:       "week",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `has(candidate.cooking_methods, "deep_fry") && countWeek("cooking_methods", "deep_fry") >= 2 ? -20 : 0`,
			Template:    `{"type":"limit","scope":"week","category":"deep_fry","n":2,"points":20,"strength":"prefer"}`,
			Priority:    250,
			Message:     "一周油炸过多降分",
		},
		{
			Code:        "non_favorite_penalty",
			Name:        "未收藏的菜降分",
			Description: "收藏过的菜代表家里会做；没收藏的菜推荐时降一点分，但不会完全消失。",
			Enabled:     true,
			Scope:       "candidate",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `!candidate.favorite ? -12 : 0`,
			Template:    `{"type":"avoid","scope":"meal","category":"non_favorite","n":1,"points":12,"strength":"prefer"}`,
			Priority:    260,
			Message:     "未收藏的菜降分",
		},
		{
			Code:        "unfamiliar_category_penalty",
			Name:        "陌生菜系降分",
			Description: "一道收藏都没有的菜系视为基本不会做，整体大幅降分；偶尔出现就当学新菜的机会。",
			Enabled:     true,
			Scope:       "candidate",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `candidate.category != "" && candidate.category_favorites == 0 ? -25 : 0`,
			Template:    `{"type":"avoid","scope":"meal","category":"unfamiliar_category","n":1,"points":25,"strength":"prefer"}`,
			Priority:    270,
			Message:     "陌生菜系降分",
		},
		{
			Code:        "weekday_slow_soup_penalty",
			Name:        "工作日少排费时汤",
			Description: "周一到周五的汤位优先快手汤；炖煮超过 45 分钟或难度高的汤留给周末。",
			Enabled:     true,
			Scope:       "candidate",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `!is_weekend && candidate.dish_role == "soup" && (candidate.cook_time > 45 || candidate.difficulty == "hard") ? -30 : 0`,
			Template:    `{"type":"avoid","scope":"meal","category":"weekday_slow_soup","n":1,"points":30,"strength":"prefer"}`,
			Priority:    280,
			Message:     "工作日费时汤降分",
		},
	}
}
