package models

func DefaultMenuRules() []MenuRule {
	return []MenuRule{
		{
			Code:        "avoid_double_egg",
			Name:        "同餐蛋类最多一份",
			Description: "避免一餐同时出现番茄炒蛋、金钱蛋、蛋花汤等多个蛋类菜。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "constraint",
			Severity:    "hard",
			Relaxable:   false,
			Expression:  `!has(candidate.protein_sources, "egg") || countMeal("protein_sources", "egg") == 0`,
			Priority:    10,
			Message:     "同餐蛋类已达到上限",
		},
		{
			Code:        "limit_cold_dishes",
			Name:        "同餐凉菜最多一份",
			Description: "避免一餐里凉菜、冷食过多。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "constraint",
			Severity:    "hard",
			Relaxable:   false,
			Expression:  `candidate.serving_temperature != "cold" || countMeal("serving_temperature", "cold") == 0`,
			Priority:    20,
			Message:     "同餐凉菜已达到上限",
		},
		{
			Code:        "limit_staples",
			Name:        "同餐主食最多一份",
			Description: "避免米线、炒饭、饼类等主食在同一餐重复出现。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "constraint",
			Severity:    "hard",
			Relaxable:   false,
			Expression:  `candidate.dish_role != "staple" || countMeal("dish_role", "staple") == 0`,
			Priority:    30,
			Message:     "同餐主食已达到上限",
		},
		{
			Code:        "avoid_same_primary_protein",
			Name:        "同餐主蛋白重复降分",
			Description: "明显重复的主蛋白会降低排序，但不硬性拦截。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `countOverlapMeal("protein_sources", candidate.protein_sources) > 0 && !hasOnly(candidate.protein_sources, "soy") ? -14 : 0`,
			Priority:    40,
			Message:     "同餐主蛋白重复降分",
		},
		{
			Code:        "quick_profile_bonus",
			Name:        "快手画像加分",
			Description: "快手模式优先短时间、简单菜。",
			Enabled:     true,
			Scope:       "candidate",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `profile == "quick" && (candidate.difficulty == "easy" || candidate.cook_time <= 25) ? 24 : 0`,
			Priority:    100,
			Message:     "快手菜加分",
		},
		{
			Code:        "light_profile_bonus",
			Name:        "清淡画像加分",
			Description: "清淡模式优先低辣、低厚重度和汤菜。",
			Enabled:     true,
			Scope:       "candidate",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `profile == "light" && candidate.spice_level == 0 && candidate.richness_level <= 1 ? 22 : 0`,
			Priority:    110,
			Message:     "清淡菜加分",
		},
		{
			Code:        "spicy_profile_bonus",
			Name:        "辣味画像加分",
			Description: "想吃辣时优先有辣度的菜。",
			Enabled:     true,
			Scope:       "candidate",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `profile == "spicy" && candidate.spice_level > 0 ? 24 : 0`,
			Priority:    120,
			Message:     "辣味菜加分",
		},
		{
			Code:        "favorite_profile_bonus",
			Name:        "收藏画像加分",
			Description: "收藏模式优先收藏菜。",
			Enabled:     true,
			Scope:       "candidate",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `profile == "favorite" && candidate.favorite ? 36 : 0`,
			Priority:    130,
			Message:     "收藏菜加分",
		},
		{
			Code:        "hot_cold_balance_bonus",
			Name:        "冷热搭配加分",
			Description: "已有热菜时给一份凉菜少量加分，已有凉菜时热菜加分。",
			Enabled:     true,
			Scope:       "meal",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `(candidate.serving_temperature == "cold" && countMeal("serving_temperature", "hot") > 0) || (candidate.serving_temperature == "hot" && countMeal("serving_temperature", "cold") > 0) ? 6 : 0`,
			Priority:    200,
			Message:     "冷热搭配加分",
		},
		{
			Code:        "avoid_heavy_spicy_day",
			Name:        "重油重辣不连续",
			Description: "同一天已有重油重辣菜时，降低后续重油重辣候选。",
			Enabled:     true,
			Scope:       "day",
			RuleKind:    "score",
			Severity:    "soft",
			Relaxable:   true,
			Expression:  `candidate.spice_level >= 2 && candidate.richness_level >= 2 && countDay("heavy_spicy", "true") > 0 ? -18 : 0`,
			Priority:    210,
			Message:     "同日重油重辣降分",
		},
	}
}
